name: Node.js Code Linting and API Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      

      - name: Make API request using curl
        run: |
          curl -X GET https://api.render.com/deploy/srv-cn6fdnud3nmc739io5v0?key=FoSG5Dl10IE
